name: Staging Deploy

on:
  pull_request:
    types: ['labeled', 'synchronize']
  label:
    types: [ 'created', 'edited' ]
jobs:
  staging_deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/github-script@v7
        id: deploy_target
        with:
          script: |
            console.log(context)
          result-encoding: 'string'
