name: Staging Deploy

on:
  pull_request:
    types: [ 'labeled', 'synchronize' ]
jobs:
  get_target:
    runs-on: ubuntu-22.04
    outputs:
      target: ${{ steps.step1.outputs.test }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/github-script@v7
        id: deploy_target
        if: ${{ !inputs.target }}
        with:
          script: |
            const script = require('.github/workflows/scripts/branch.js')
            return script({github, context});
          result-encoding: 'string'
      - name: set target output
        run: | 
          echo 'target=${{steps.deploy_target.outputs.result}}' >> "$GITHUB_OUTPUT"
          echo 'TARGET=${{steps.deploy_target.outputs.result}}' >> "$GITHUB_ENV"
  update_environment:
    runs-on: ubuntu-22.04
    needs: get_target
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        id: deploy_target
        if: ${{ !inputs.target }}
        with:
          script: console.log('Setting up environment %{{jobs.get_target.outputs.target}} ')
  deploy:
    runs-on: ubuntu-22.04
    needs: update_environment
    if: |
      always() &&
      !contains(needs.update_environment.result, 'failure') &&
      !contains(needs.update_environment.result, 'cancelled')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        id: deploy_target
        if: ${{ !inputs.target }}
        with:
          script: console.log('Deploying to %{{jobs.get_target.outputs.target}} ')
